# Generated by Django 4.2.14 on 2025-01-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeManager', '0004_order_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='stock_state',
            field=models.IntegerField(default=0),
        ),
    ]
