# Generated by Django 4.2.14 on 2025-01-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeManager', '0005_alter_orderitem_stock_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='stock_state',
            field=models.BooleanField(default=False),
        ),
    ]
